import '../../api/posts/methods.js'
import '../../api/posts/server/publications.js'
import '../../api/users/methods.js'
import '../../api/users/server/publications.js'
import '../../api/chats/methods.js'
import '../../api/chats/server/publications.js'
import {createNewProfiles} from './profilesScript.js'